name: grid_play
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/icon/icon.png
  - assets/icon/splash.png
  - assets/icon/icon-transparente.png

flutter_icons:
  image_path: "assets/icon/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground:

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/icon-transparente.png"
  android: true
  ios: true
